export const ROOT = '/'
export const APP_PREFIX_PATH = '/app'
export const AUTH_PREFIX_PATH = '/auth'
export const UI_COMPONENTS_PREFIX_PATH = '/ui-components'
export const PAGES_PREFIX_PATH = '/pages'
export const DOCS_PREFIX_PATH = '/docs'

//export const API_SERVER_IP = 'http://api.wikl.ink'
//export const API_SERVER_PORT="80";
export const API_SERVER_IP = 'https://localhost'
export const API_SERVER_PORT="44332";
export const API_SERVER_PREFIX="/api";
export const API_SERVER=API_SERVER_IP+":"+API_SERVER_PORT+API_SERVER_PREFIX;
export const API_SERVER_AUTH_PREFIX = '/security'
export const API_SERVER_PRODUCT_PREFIX = '/product'
export const API_SERVER_COMPANY_PREFIX = '/company'
export const API_SERVER_GENERAL_PREFIX = '/general'
export const API_SERVER_PEOPLE_PREFIX = '/people'
export const API_SERVER_ORDER_PREFIX = '/order'
export const API_SERVER_BRANCH_PREFIX = '/branch'
export const API_SERVER_STORES_PREFIX = '/store'
export const API_SERVER_BANK_ACCOUNT_PREFIX = '/bank-account'
export const API_SERVER_DASHBOARD_PREFIX = '/sales'
